config/routes.rb
Rails.application.routes.draw do

  resources :games
  get 'sessions/new'
  root 'users#start'
  
  get 'start/options' => 'games#options', as: :options
  get 'start/actions' => 'games#actions', as: :actions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  
  get '/users/new_voter', to: 'users#new_voter', as: :new_voter
  get '/users/new_politician', to: 'users#new_politician', as: :new_politician
  post '/users/:id/add_policy', to: 'policies#add_policy_to_user', as: :add_policy_to_user
  post '/users/:id/increase_vote_count', to: 'users#increase_vote_count', as: :increase_vote_count 
  post '/users/:id/add_party', to: 'parties#add_party_to_user', as: :add_party_to_user
  post '/users/:id/add_scandal', to: 'scandals#add_scandal_to_user', as: :add_scandal_to_user
  post '/users/:id/add_debate', to: 'debates#add_debate_to_user', as: :add_debate_to_user
  


  resources :debates
  resources :scandals
  resources :parties
  resources :policies
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/debate.rb
class Debate < ApplicationRecord
    has_many :user_debates
    has_many :users, through: :user_debates
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }

end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/party.rb
class Party < ApplicationRecord
    has_many :user_parties
    has_many :users, through: :user_parties
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }
    def self.link_party_to_user(current_user_id, party_id)
        @user = User.find(current_user_id)
        UserParty.find_or_create_by(user_id: @user.id, party_id: party_id) 
        @user
    end
    
end

app/models/policy.rb
class Policy < ApplicationRecord
    has_many :user_policies
    has_many :users, through: :user_policies
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }

    def self.link_policy_to_user(current_user_id, policy_id)
        @user = User.find(current_user_id)
        UserPolicy.find_or_create_by(user_id: @user.id, policy_id: policy_id) 
        @user
    end
end

app/models/scandal.rb
class Scandal < ApplicationRecord
    has_many :user_scandals
    has_many :users, through: :user_scandals
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_scandals
    has_many :scandals, through: :user_scandals
    has_many :user_policies
    has_many :policies, through: :user_policies
    has_many :user_parties
    has_many :parties, through: :user_parties
    has_many :user_debates
    has_many :debates, through: :user_debates

    has_many :reported_user_scandals, class_name: 'UserScandal', foreign_key: 'giver_id'
    has_many :reported_scandals, through: :reported_user_scandals, source: :scandal


    has_many :votes, foreign_key: :politician_id
    #creates a method that grabs the voter in a given Vote instance and allows a politician to see who has voted for them
    has_many :votees, through: :votes, source: :voter 

    #going through votes to grab all politicians a user has voted for
    has_many :voted_fors, class_name: 'Vote', foreign_key: :voter_id #all vote instances you participated in as voter
    has_many :politicians_voted_for, through: :voted_fors, source: :politician # just the politicians from previous array

    has_secure_password

    #validates :password, length: { is: 5 }
    #validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }
    #validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

    TITLES = ['Law Abiding Citizen', 'City Councillor', 'Mayor', 'State Representative', 'House Representative', 'Senator', 'President']

    def evolve(politician_id)
        @politician = User.find_by(id: politician_id)
        case @politician.vote_count 
        when 0
            @politician.update_attribute(:title, TITLES[0])
        when 1
            @politician.update_attribute(:title, TITLES[1])
        when 2
            @politician.update_attribute(:title, TITLES[2])
        when 3
            @politician.update_attribute(:title, TITLES[3])
        when 4
            @politician.update_attribute(:title, TITLES[4])
        when 5
            @politician.update_attribute(:title, TITLES[5])
        else 
            @politician.update_attribute(:title, TITLES[6])
        end
    end

    def is_politician?
        politician
    end

    def upvote(voter_id, politician_id) 
        @politician = User.find(politician_id)     
        if self.already_voted_for?(voter_id, politician_id)
            total = @politician.vote_count += 0
            @politician.update_attribute(:vote_count, total)  
        else
            Vote.create(voter_id: voter_id.to_i , politician_id: @politician.id) 
            total = @politician.vote_count += 1
            @politician.update_attribute(:vote_count, total) 
            @politician.evolve(politician_id)  
        end
    end 

    def already_voted_for?(voter_id, politician_id)
        Vote.all.each do |v|
            if (v.voter_id == voter_id.to_i) && (v.politician_id == politician_id.to_i)
                return true
            end 
        end
        false   
    end

    # def party_limit_one
    #     @user = User.find(params[:id])
    #     @user.parties.take(1)
    #     return 'you must leave a party before joining another' 
    # end
   
    def self.all_politicians
        all.select {|user| user.is_politician?}
    end

    def self.all_politicians_sorted_by_vote_count
        all_politicians.sort_by(&:vote_count).reverse
    end

    def self.all_voters
        all.select {|user| !user.is_politician?}
    end

end

app/models/user_debate.rb
class UserDebate < ApplicationRecord
    belongs_to :user
    belongs_to :debate 
end

app/models/user_party.rb
class UserParty < ApplicationRecord
    belongs_to :user
    belongs_to :party 
end

app/models/user_policy.rb
class UserPolicy < ApplicationRecord
    belongs_to :user
    belongs_to :policy 
end

app/models/user_scandal.rb
class UserScandal < ApplicationRecord
    belongs_to :user
    belongs_to :scandal 

    belongs_to :giver, class_name: 'User'
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :voter, class_name: 'User'
    belongs_to :politician, class_name: 'User'
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :update, :destroy]
  
  def start
  end

  def index
    @users = User.all
    @user = User.find(session[:user_id])
  end

  def new 
    @user = User.new 
  end

  def new_voter
    @user = User.new 
  end

  def new_politician
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      return redirect_to login_path unless @user.save
      session[:user_id] = @user.id
      redirect_to users_path
  end

  def show 
    @current_user = User.find_by(id: session['user_id'])
  end

  def increase_vote_count
    @user = User.find_by(id: params[:id])
    @user.upvote(session[:user_id], @user.id)
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find_by(id: params[:id])
    @current_user = User.find_by(id: session['user_id'])
  end

  def update
  if @user.update(user_params)
    redirect_to @user 
  else
    render :edit
  end
end

  private
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :photo, :age, :race, :gender, :location, :politician, :title, :running_mate_name, :running_mate_photo, :level, :vote_count, :bio, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/policiess_helper.rb
module PoliciessHelper
end

app/helpers/scandals_helper.rb
module ScandalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Vendor CSS-->
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/main.css" rel="stylesheet" media="all">
</head>
<style>
        body {
            background: url(https://live.staticflickr.com/3174/2690293634_8557a484b1_b.jpg); 
           }
    
           .blue-img {
            background-image: url(/images/img01.jpg);
            display: block;
            margin: 0 auto;
            width: 70%;
            position: relative;
            top: 65px;
            padding: 60px 0;
           }
    
           .innerWrapper {
               width: 80%;
               margin: auto;
    
           }
    
           #new_menu {
            position: absolute;
            right: 100px;
            width: 500px;
            height: 90px;
            margin: 0 auto;
            padding: 0;
            z-index: 100;
        }
        
        #new_menu ul {
            float: right;
            margin: 0;
            padding: 20px 0px 0px 0px;
            list-style: none;
            line-height: normal;
        }
        
        #new_menu li {
            float: left;
        }
        
        #new_menu a {
            display: block;
            margin-right: 1px;
            padding: 0px 20px 0px 20px;
            text-decoration: none;
            text-align: center;
            text-shadow: 1px 1px 0px rgba(0,0,0,.2);
            text-transform: uppercase;
            font-family: 'Oswald', sans-serif;
            font-size: 16px;
            font-weight: 300;
            color: #FFFFFF;
            border: none;
        }
        
        #new_menu a:hover, #new_menu .current_page_item a {
            text-decoration: none;
            color: #FFFFFF;
        }
        
        #new_menu .current_page_item a {
        }
        
</style>
<body>
        <div id="new_menu">
                <ul>
                    <li class="current_page_item"><a href="<%= root_path %>">Homepage</a></li>
                    <li><a href="<%= parties_path %>">Parties</a></li>
                    <li><a href="<%= policies_path %>">Policies</a></li>
                    <li><a href="<%= scandals_path %>">Scandals</a></li>
                   
                </ul>
            </div>
    <div class="blue-img">
        <div class="innerWrapper">
            <div class="card card-1">
                    <div class="card-heading"></div>
                    <div class="card-body">
            <h2 class="title">Update Profile Information</h2>
            
    <%= form_for(@user, :html => {:class => "input-group"}) do |f| %>
    <%= f.hidden_field :politician, value: true %>
    <div class="input-group">   
        <%= f.text_field(:name, placeholder: 'FULL NAME', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>

    <div class="input-group">   
        <%= f.text_field(:email, placeholder: 'EMAIL', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>

    <div class="input-group">   
        <%= f.text_field(:password, placeholder: 'PASSWORD', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>

    <div class="input-group">   
        <%= f.text_field(:photo, placeholder: 'UPLOAD PHOTO', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>

    <div class="input-group">   
        <%= f.text_field(:age, placeholder: 'AGE', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>

    <div class="input-group">   
        <%= f.select(:race, ['CHOOSE RACE', 'White', 'Black or African American', 'American Indian and Alaska Native', 'Asian', 
        'Native Hawaiian and Other Pacific Islander'], {}, {:class => "rs-select2 js-select-simple select--no-search"}) %><br>
        <div class="select-dropdown"></div>
    </div>

    <div class="input-group">   
        <%= f.select(:gender, ['CHOOSE GENDER', 'Male', 'Female', 'Other'], {}, {:class => "rs-select2 js-select-simple select--no-search"}) %><br>
        <div class="select-dropdown"></div>
    </div>
  
    <div class="input-group">  
        <%= f.select(:location, %w(STATE\ OF\ RESIDENCE Alabama Alaska Arizona Arkansas California Colorado Connecticut Delaware
        Florida Georgia Hawaii Idaho Illinois Indiana Iowa Kansas Kentucky Louisiana
        Maine Maryland Massachusetts Michigan Minnesota Mississippi Missouri Montana
        Nebraska Nevada New\ Hampshire New\ Jersey New\ Mexico New\ York North\ Carolina
        North\ Dakota Ohio Oklahoma Oregon Pennsylvania Rhode\ Island South\ Carolina
        South\ Dakota Tennessee Texas Utah Vermont Virginia Washington West\ Virginia
        Wisconsin Wyoming), {}, {:class => "rs-select2 js-select-simple select--no-search"}) %><br>
        <div class="select-dropdown"></div>
    </div> 

    <% if @user.is_politician? %>

    <div class="input-group">   
        <%= f.select(:title, ['Law Abiding Citizen'], {}, {:class => "rs-select2 js-select-simple select--no-search"}) %><br>
        <div class="select-dropdown"></div>
    </div>

    <div class="input-group">   
            <%= f.text_field(:running_mate_name, placeholder: 'RUNNING MATE', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>
    
    <div class="input-group">   
        <%= f.text_field(:running_mate_photo, placeholder: 'UPLOAD RUNNING MATE PHOT', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>
  <% end %>
    <div class="input-group">   
        <%= f.text_field(:bio, placeholder: 'YOUR BIOGRAPHY', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>

    <!-- <div class="row row-space">
            <div class="col-2">
        <div class="row row-space">
            <div class="col-2">
        <div class="p-t-20"> -->
             <%= f.submit class: "btn btn--radius btn--green" %>
    <% end %><br>
        </div>
        </div>
</div>

<script src="https://colorlib.com/etc/regform/colorlib-regform-1/js/global.js"></script>
</body>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link
      href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
      rel="stylesheet"
    />

    <title>Reflux HTML CSS Template</title>
<!--
Reflux Template
https://templatemo.com/tm-531-reflux
-->
    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="assets/css/fontawesome.css" />
    <link rel="stylesheet" href="assets/css/templatemo-style.css" />
    <link rel="stylesheet" href="assets/css/owl.css" />
    <link rel="stylesheet" href="assets/css/lightbox.css" />
  </head>

  <body>
    <div id="page-wraper">
    
      <section class="section about-me" data-section="section1">
        <div class="container">
          <div class="section-heading">
            <h2><%= @user.name %></h2>
            <div class="line-dec right-text" ></div>
            <h2><%= @user.bio %> </h2
            >
            
          </div>
          <div class="left-image-post">
            <div class="row">
              <div class="col-md-6">
                <div class="left-image">
                  <%= image_tag @user.photo %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="right-text" >
                  <h2>Personal Information</h2>
                  <br>
                    <h3> Age: <%= @user.age %> </h3><br>
                    <h3>Race: <%= @user.race %> </h3><br>
                    <h3> Gender: <%= @user.gender %> </h3><br>
                    <h3>Location: <%= @user.location %> </h3><br>
                  <br>
                </div>
              </div>
            </div>
          </div>
          <% if @user.is_politician? %>
          <div class="right-image-post">
            <div class="row">
              <div class="col-md-6">
                <div class="right-text">
                  <h2>My Running Mate</h2>
                  <br>
                  <h3>
                    Allow me to introduce my running mate. Running mates are extremely useful, and <%= @user.running_mate_name %>
                    is absolutely one of the best. It's truly a blessing to know this person. Bring your baby to an event, 
                    <%= @user.running_mate_name %> will kiss it on the head in a totally not staged photo-op.
                  </h3>
                </div>
              </div>
              <div class="col-md-6">
                <div class="right-image">
                  <img src="<%= @user.running_mate_photo %>">
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <% end %>
      <section class="section my-services" data-section="section2">
        <div class="container">
          <div class="section-heading">
            <div class="right-text">
            <h2>Party Affiliation</h2>
            <div class="line-dec"></div>
            <% if @user.parties.present? %>
            <% @user.parties.each do |p| %>
            <div class="right-text">
            <h3 class="right-text">I am a card carrying member of the <%= link_to  p.name, party_path(p), {:style=> 'color:#5afffd'} %> Party.</h3
            >
            <br>
            <img src="<%= p.photo %>">
            <% end %>
            <% else %>
            <h3
              >I am not a card carrying member of a <%= link_to  "Party", parties_path, {:style=> 'color:#5afffd'} %> at present.</h3
            >
            <% end %>
          </div>
          <div class="row">
            <div class="col-md-6">
              
            </div>
            <div class="col-md-6">
              
            </div>
            <div class="col-md-6">
            </div>
          </div>
        </div>
      </section>

      <section class="section my-work" data-section="section3">
        <div class="container">
          <div class="section-heading">
            <h2>On The Issues</h2>
            <div class="line-dec"></div>
            <div class="right-text">
            <% if @user.policies.present? %>
            <% @user.policies.each do |pol| %>
            <div class="right-text">
            <h3><%= link_to pol.title, policy_path(pol), {:style=> 'color:#5afffd'} %><br></h3>
            </div>
            <% end %>
        <% else %>
            <h3>Add or Create a new <%= link_to  "Policy Point", policies_path, {:style=> 'color:#5afffd'} %> to have it display here!</h3>
        <% end %>
            </div>
          </div>
          <div class="row">
            <div class="isotope-wrapper">
              <div class="isotope-box">
               
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="section my-work" data-section="section3">
        <div class="container">
          <div class="section-heading">
            <% if @user.is_politician? %>
                <h2>Scandals You Are Involved In</h2>
                    <div class="line-dec"></div>
                    <div class="right-text">
                        <% if @user.scandals.present? %>
                            <% @user.scandals.each do |s| %>
                                <h3><%= link_to s.title, scandal_path(s), {:style=> 'color:#5afffd'} %></h3><br>
                                <% end %>
                        <% else %>
                                <h3> You're currently as clean as a whistle. We're surprised, frankly! Don't screw this up!</h3>
                        <% end %>
            <% else %>
              <h2>Scandals You Have Uncovered</h2>
              <div class="line-dec"></div>
                    <div class="right-text">
                        <% if @user.reported_scandals.present? %>
                            <% @user.reported_scandals.each do |s| %>
                                <h3><%= link_to s.title, scandal_path(s), {:style=> 'color:#5afffd'} %></h3><br>
                                <% end %>
                        <% else %>
                                <h3>Spill the dirt on a politician by bringing a new <%= link_to  "Scandal", new_scandal_path %> to light!</h3>
                        <% end %>
            <% end %>
            </div>
          </div>
          <div class="row">
            <div class="isotope-wrapper">
              <div class="isotope-box">
              </div>
            </div>
          </div>
        </div>
      </section>
    </section>
    <section class="section my-work" data-section="section3">
      <div class="container">
        <div class="section-heading">
          <h2>Debate Information</h2>
          <div class="line-dec"></div>
          <div class="right-text">
          <h3> Information Coming Soon</h3>
        </div>
    </div>
        <div class="row">
          <div class="isotope-wrapper">
            <div class="isotope-box">
            </div>
          </div>
        </div>
      </div>
    </section>
    <% if @user.is_politician? %>
    <section class="section my-work" data-section="section3">
      <div class="container">
        <div class="section-heading">
          <h2>Vote For Me!</h2>

          <div class="line-dec"></div>
          <div class="right-text">
          <h3>Click Below to Vote For Me!:</h3>
          <br>
          <button><%= button_to 'Vote For Me!', action: 'increase_vote_count', params: {voter_id: session[:user_id], politician_id: @user.id} %></button>
          <br>
          <!-- <button type="submit" id="form-submit" class="button">
            Vote NOW!
          </button> -->
          <br>
          <h1>My Current Vote Count is <%= @user.vote_count %></h1>
          <br>
          <br>
          <br>
        </div>
       <h2>Others Who Have Voted For Me</h2>
       <br>
       <div class="right-text">
       <% if @user.votees.present? %>
              <% @user.votees.each do |c| %>
              <h3><%= link_to c.name, user_path(c), {:style=> 'color:#5afffd'} %></h3><br>
              <% end %>
          <% else %>
              <h3>Get out there and talk to some <%= link_to "voters", users_path, {:style=> 'color:#5afffd'} %>!</h3>
          <% end %><br>
        </div>
        </div>
    </section>
    <% else %>
    <section class="section my-work" data-section="section3">
            <div class="container">
              <div class="section-heading">
                <h2>See Your Votes</h2>
                <div class="line-dec"></div>
             <div class="right-text">
             <% if @user.politicians_voted_for.present? %>
                    <% @user.politicians_voted_for.each do |c| %>
                    <h3><%= link_to c.name, user_path(c), {:style=> 'color:#5afffd'} %></h3><br>
                    <% end %>
                <% else %>
                    <h3> <%= link_to "Vote", users_path %> now to show the world your true allegiances!</h3>
                <% end %><br>
              </div>
              </div>
          </section>
        <% end %>
    <% if @user.is_politician? %>
      <section class="section contact-me" data-section="section4">
        <div class="container">
          <div class="section-heading">
                <div class="right-text">
            <h2>Contact Me</h2>
            <div class="line-dec"></div>
            <h3
              >As a politician, I am extremely, actually, really interested in what you have to say. If you write to me, I will personally read every line and respond. Swear to God! I don't have a team that handles this sort of thing, I'm not like my untrustworthy, unpatriotic, freedom hating, ugly opponents.</h3
            >
        </div>
          </div>
          <div class="row">
            <div class="right-content">
              <div class="container">
                <form id="contact">
                  <div class="row">
                    <div class="col-md-6">
                            
                      <fieldset>
                            
                        <input 
                          name="name"
                          type="text"
                          class="form-control right-text"
                          id="name"
                          placeholder="Your name..."
                          required=""
                        />
                    
                      </fieldset>
                    </div>
                    <div class="col-md-6">
                      <fieldset>
                        <input
                          name="email"
                          type="text"
                          class="form-control"
                          id="email"
                          placeholder="Your email..."
                          required=""
                        />
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <input
                          name="subject"
                          type="text"
                          class="form-control"
                          id="subject"
                          placeholder="Subject..."
                          required=""
                        />
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <textarea
                          name="message"
                          rows="6"
                          class="form-control"
                          id="message"
                          placeholder="Your message..."
                          required=""
                        ></textarea>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <button  id="form-submit" class="button" onClick="alert('Great, someone is totally going to actually read that and get back to you. You know it is true because you cannot lie on the internet.')">
                          Send Message
                        </button>
                      </fieldset>
                    </div>
                  </div>
                </form>
                <% end %>
                <%= button_to "Edit Your Personal Information By Clicking Here", edit_user_path(@user), {method: :get} %><br>
                <%= button_to  "Back to All Users", users_path, {method: :get} %><br>
                <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
                <input type=submit value='logout'>
                <% end %>
                </div>   
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
</div>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="assets/js/isotope.min.js"></script>
    <script src="assets/js/owl-carousel.js"></script>
    <script src="assets/js/lightbox.js"></script>
    <script src="assets/js/custom.js"></script>
   
  </body>
</html>