config/routes.rb
Rails.application.routes.draw do

  resources :games
  get 'sessions/new'
  root 'users#start'
  
  get 'start/options' => 'games#options', as: :options
  get 'start/actions' => 'games#actions', as: :actions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  
  get '/users/new_voter', to: 'users#new_voter', as: :new_voter
  get '/users/new_politician', to: 'users#new_politician', as: :new_politician
  post '/users/:id/add_policy', to: 'policies#add_policy_to_user', as: :add_policy_to_user
  post '/users/:id/increase_vote_count', to: 'users#increase_vote_count', as: :increase_vote_count 
  post '/users/:id/add_party', to: 'parties#add_party_to_user', as: :add_party_to_user
  post '/users/:id/add_scandal', to: 'scandals#add_scandal_to_user', as: :add_scandal_to_user
  post '/users/:id/add_debate', to: 'debates#add_debate_to_user', as: :add_debate_to_user
  


  resources :debates
  resources :scandals
  resources :parties
  resources :policies
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/debate.rb
class Debate < ApplicationRecord
    has_many :user_debates
    has_many :users, through: :user_debates
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }

end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/party.rb
class Party < ApplicationRecord
    has_many :user_parties
    has_many :users, through: :user_parties
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }
    def self.link_party_to_user(current_user_id, party_id)
        @user = User.find(current_user_id)
        UserParty.find_or_create_by(user_id: @user.id, party_id: party_id) 
        @user
    end
    
end

app/models/policy.rb
class Policy < ApplicationRecord
    has_many :user_policies
    has_many :users, through: :user_policies
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }

    def self.link_policy_to_user(current_user_id, policy_id)
        @user = User.find(current_user_id)
        UserPolicy.find_or_create_by(user_id: @user.id, policy_id: policy_id) 
        @user
    end
end

app/models/scandal.rb
class Scandal < ApplicationRecord
    has_many :user_scandals
    has_many :users, through: :user_scandals
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_scandals
    has_many :scandals, through: :user_scandals
    has_many :user_policies
    has_many :policies, through: :user_policies
    has_many :user_parties
    has_many :parties, through: :user_parties
    has_many :user_debates
    has_many :debates, through: :user_debates

    has_many :reported_user_scandals, class_name: 'UserScandal', foreign_key: 'giver_id'
    has_many :reported_scandals, through: :reported_user_scandals, source: :scandal


    has_many :votes, foreign_key: :politician_id
    #creates a method that grabs the voter in a given Vote instance and allows a politician to see who has voted for them
    has_many :votees, through: :votes, source: :voter 

    #going through votes to grab all politicians a user has voted for
    has_many :voted_fors, class_name: 'Vote', foreign_key: :voter_id #all vote instances you participated in as voter
    has_many :politicians_voted_for, through: :voted_fors, source: :politician # just the politicians from previous array

    has_secure_password

    #validates :password, length: { is: 5 }
    #validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }
    #validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

    TITLES = ['Law Abiding Citizen', 'City Councillor', 'Mayor', 'State Representative', 'House Representative', 'Senator', 'President']

    def evolve(politician_id)
        @politician = User.find_by(id: politician_id)
        case @politician.vote_count 
        when 0
            @politician.update_attribute(:title, TITLES[0])
        when 1
            @politician.update_attribute(:title, TITLES[1])
        when 2
            @politician.update_attribute(:title, TITLES[2])
        when 3
            @politician.update_attribute(:title, TITLES[3])
        when 4
            @politician.update_attribute(:title, TITLES[4])
        when 5
            @politician.update_attribute(:title, TITLES[5])
        else 
            @politician.update_attribute(:title, TITLES[6])
        end
    end

    def is_politician?
        politician
    end

    def upvote(voter_id, politician_id) 
        @politician = User.find(politician_id)     
        if self.already_voted_for?(voter_id, politician_id)
            total = @politician.vote_count += 0
            @politician.update_attribute(:vote_count, total)  
        else
            Vote.create(voter_id: voter_id.to_i , politician_id: @politician.id) 
            total = @politician.vote_count += 1
            @politician.update_attribute(:vote_count, total) 
            @politician.evolve(politician_id)  
        end
    end 

    def already_voted_for?(voter_id, politician_id)
        Vote.all.each do |v|
            if (v.voter_id == voter_id.to_i) && (v.politician_id == politician_id.to_i)
                return true
            end 
        end
        false   
    end

    # def party_limit_one
    #     @user = User.find(params[:id])
    #     @user.parties.take(1)
    #     return 'you must leave a party before joining another' 
    # end
   
    def self.all_politicians
        all.select {|user| user.is_politician?}
    end

    def self.all_politicians_sorted_by_vote_count
        all_politicians.sort_by(&:vote_count).reverse
    end

    def self.all_voters
        all.select {|user| !user.is_politician?}
    end

end

app/models/user_debate.rb
class UserDebate < ApplicationRecord
    belongs_to :user
    belongs_to :debate 
end

app/models/user_party.rb
class UserParty < ApplicationRecord
    belongs_to :user
    belongs_to :party 
end

app/models/user_policy.rb
class UserPolicy < ApplicationRecord
    belongs_to :user
    belongs_to :policy 
end

app/models/user_scandal.rb
class UserScandal < ApplicationRecord
    belongs_to :user
    belongs_to :scandal 

    belongs_to :giver, class_name: 'User'
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :voter, class_name: 'User'
    belongs_to :politician, class_name: 'User'
    # validates_presence_of attribute_names.reject { |attr| attr =~ /id|created_at|updated_at/i }
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :find_policy, only: [:show, :edit, :update, :destroy]
  def index
    @policies = Policy.all 
  end

  def new
    @policy = Policy.new 
  end

  def create
    @policy = Policy.new(policy_params)
      if @policy.save 
        redirect_to @policy 
      else
        render :new 
      end
  end

  def show
  end

  def edit
  end

  def add_policy_to_user
    redirect_to user_path(Policy.link_policy_to_user(params[:user_id], params[:policy_id]))
  end
  
  def update 
    if @policy.update(policy_params)
      redirect_to @policy 
    else
      render :edit 
    end
  end

  def destroy
    @policy.destroy 
    redirect_to policies_path 
  end


  private

  def find_policy
    @policy = Policy.find(params[:id])
  end

  def policy_params 
    params.require(:policy).permit(:title, :content, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/policiess_helper.rb
module PoliciessHelper
end

app/helpers/scandals_helper.rb
module ScandalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/policies/edit.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Vendor CSS-->
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/main.css" rel="stylesheet" media="all">
</head>
<style>
        body {
            background: url(https://live.staticflickr.com/3174/2690293634_8557a484b1_b.jpg); 
           }
    
           .blue-img {
            background-image: url(/images/img01.jpg);
            display: block;
            margin: 0 auto;
            width: 70%;
            position: relative;
            top: 65px;
            padding: 60px 0;
           }
    
           .innerWrapper {
               width: 80%;
               margin: auto;
    
           }
    
           #new_menu {
            position: absolute;
            right: 100px;
            width: 500px;
            height: 90px;
            margin: 0 auto;
            padding: 0;
            z-index: 100;
        }
        
        #new_menu ul {
            float: right;
            margin: 0;
            padding: 20px 0px 0px 0px;
            list-style: none;
            line-height: normal;
        }
        
        #new_menu li {
            float: left;
        }
        
        #new_menu a {
            display: block;
            margin-right: 1px;
            padding: 0px 20px 0px 20px;
            text-decoration: none;
            text-align: center;
            text-shadow: 1px 1px 0px rgba(0,0,0,.2);
            text-transform: uppercase;
            font-family: 'Oswald', sans-serif;
            font-size: 16px;
            font-weight: 300;
            color: #FFFFFF;
            border: none;
        }
        
        #new_menu a:hover, #new_menu .current_page_item a {
            text-decoration: none;
            color: #FFFFFF;
        }
        
        #new_menu .current_page_item a {
        }
        
</style>
<body>
        <div id="new_menu">
                <ul>
                    <li class="current_page_item"><a href="<%= root_path %>">Homepage</a></li>
                    <li><a href="<%= parties_path %>">Parties</a></li>
                    <li><a href="<%= policies_path %>">Policies</a></li>
                    <li><a href="<%= scandals_path %>">Scandals</a></li>
                    
                </ul>
            </div>
    <div class="blue-img">
        <div class="innerWrapper">
            <div class="card card-1">
                    <div class="card-heading"></div>
                    <div class="card-body">
            <h2 class="title">EDIT THIS POLICY</h2>

    <%= form_for @policy, :html => {:class => 'input-group'} do |f| %>
        <div class="input-group">   
        <%= f.text_field(:title, placeholder: 'POLICY TITLE', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>
<div class="input-group">   
<%= f.text_field(:content, placeholder: 'DESCRIPTION', :html => {:class => "input--style-1 js-datepicker"}) %><br>
</div>
<div class="input-group">   
<%= f.text_field(:photo, placeholder: 'UPLOAD PHOTO', :html => {:class => "input--style-1 js-datepicker"}) %><br>
</div>
<!-- <div class="row row-space">
<div class="col-2">
<div class="row row-space">
<div class="col-2">
<div class="p-t-20"> -->
 <%= f.submit class: "btn btn--radius btn--green" %>
<% end %><br>
</div>
<br>
<button><%= button_to  "Back to Policies Page", policies_path, {method: :get} %></button>

app/views/policies/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Vendor CSS-->
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/main.css" rel="stylesheet" media="all">
</head>
<style>
       body {
        background: url(https://live.staticflickr.com/3174/2690293634_8557a484b1_b.jpg); 
       }

       .blue-img {
        background-image: url(/images/img01.jpg);
        display: block;
        margin: 0 auto;
        width: 70%;
        position: relative;
        top: 65px;
        padding: 60px 0;
       }

       .innerWrapper {
           width: 80%;
           margin: auto;
           text-align: center;
       }
       #new_menu {
        position: absolute;
        right: 100px;
        width: 500px;
        height: 90px;
        margin: 0 auto;
        padding: 0;
        z-index: 100;
    }
    
    #new_menu ul {
        float: right;
        margin: 0;
        padding: 20px 0px 0px 0px;
        list-style: none;
        line-height: normal;
    }
    
    #new_menu li {
        float: left;
    }
    
    #new_menu a {
        display: block;
        margin-right: 1px;
        padding: 0px 20px 0px 20px;
        text-decoration: none;
        text-align: center;
        text-shadow: 1px 1px 0px rgba(0,0,0,.2);
        text-transform: uppercase;
        font-family: 'Oswald', sans-serif;
        font-size: 16px;
        font-weight: 300;
        color: #FFFFFF;
        border: none;
    }
    
    #new_menu a:hover, #new_menu .current_page_item a {
        text-decoration: none;
        color: #FFFFFF;
    }
    
    #new_menu .current_page_item a {
    }
    

    </style>

    <body>  
            <div id="new_menu">
                    <ul>
                        <li class="current_page_item"><a href="<%= root_path %>">Homepage</a></li>
                        <li><a href="<%= parties_path %>">Parties</a></li>
                        <li><a href="<%= policies_path %>">Policies</a></li>
                        <li><a href="<%= scandals_path %>">Scandals</a></li>
                       
                    </ul>
                </div>
        <div class="blue-img">
            <div class="innerWrapper">
                <div class="card card-1">
                        <div class="card-heading"></div>
                        <div class="card-body">
                <h2 class="title">ON THE ISSUES</h2>

                <% if session[:user_id] %>
<h3><%= link_to "Jump To Your Profile Page", user_path(session[:user_id]), {:style=> 'color:#3470da'} %></h3>

<% end %>


<h1>Click a link below to explore the nuanced depths of hard hitting issues.</h1><br>
<% @policies.each do |p| %>
   <h3><%= link_to  p.title, policy_path(p), {:style=> 'color:#3470da'} %><br></h3> 
<% end %><br>
<br>
<br>
<br>
<br>
<h3><%= link_to  "Create A New Policy", new_policy_path, {:style=> 'color:#3470da'} %></h3>
<h3><%= link_to  "Back To Main Page", root_path, {:style=> 'color:#3470da'} %></h3>

app/views/policies/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Vendor CSS-->
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/main.css" rel="stylesheet" media="all">
</head>
<style>
        body {
            background: url(https://live.staticflickr.com/3174/2690293634_8557a484b1_b.jpg); 
           }
    
           .blue-img {
            background-image: url(/images/img01.jpg);
            display: block;
            margin: 0 auto;
            width: 70%;
            position: relative;
            top: 65px;
            padding: 60px 0;
           }
    
           .innerWrapper {
               width: 80%;
               margin: auto;
    
           }
    
           #new_menu {
            position: absolute;
            right: 100px;
            width: 500px;
            height: 90px;
            margin: 0 auto;
            padding: 0;
            z-index: 100;
        }
        
        #new_menu ul {
            float: right;
            margin: 0;
            padding: 20px 0px 0px 0px;
            list-style: none;
            line-height: normal;
        }
        
        #new_menu li {
            float: left;
        }
        
        #new_menu a {
            display: block;
            margin-right: 1px;
            padding: 0px 20px 0px 20px;
            text-decoration: none;
            text-align: center;
            text-shadow: 1px 1px 0px rgba(0,0,0,.2);
            text-transform: uppercase;
            font-family: 'Oswald', sans-serif;
            font-size: 16px;
            font-weight: 300;
            color: #FFFFFF;
            border: none;
        }
        
        #new_menu a:hover, #new_menu .current_page_item a {
            text-decoration: none;
            color: #FFFFFF;
        }
        
        #new_menu .current_page_item a {
        }
        
</style>
<body>
        <div id="new_menu">
                <ul>
                    <li class="current_page_item"><a href="<%= root_path %>">Homepage</a></li>
                    <li><a href="<%= parties_path %>">Parties</a></li>
                    <li><a href="<%= policies_path %>">Policies</a></li>
                    <li><a href="<%= scandals_path %>">Scandals</a></li>
                    
                </ul>
            </div>
    <div class="blue-img">
        <div class="innerWrapper">
            <div class="card card-1">
                    <div class="card-heading"></div>
                    <div class="card-body">
            <h2 class="title">CREATE A POLICY</h2>

    <%= form_for @policy, :html => {:class => 'input-group'} do |f| %>
        <div class="input-group">   
        <%= f.text_field(:title, placeholder: 'POLICY TITLE', :html => {:class => "input--style-1 js-datepicker"}) %><br>
    </div>
<div class="input-group">   
<%= f.text_field(:content, placeholder: 'DESCRIPTION', :html => {:class => "input--style-1 js-datepicker"}) %><br>
</div>
<div class="input-group">   
<%= f.text_field(:photo, placeholder: 'UPLOAD PHOTO', :html => {:class => "input--style-1 js-datepicker"}) %><br>
</div>
<!-- <div class="row row-space">
<div class="col-2">
<div class="row row-space">
<div class="col-2">
<div class="p-t-20"> -->
 <%= f.submit class: "btn btn--radius btn--green" %>
<% end %><br>
</div>
<br>
<button><%= button_to  "Back to Policies Page", policies_path, {method: :get} %></button>

app/views/policies/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Vendor CSS-->
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/main.css" rel="stylesheet" media="all">
</head>
<style>
       body {
        background: url(https://live.staticflickr.com/3174/2690293634_8557a484b1_b.jpg); 
        
       }

       party-name {
         color: whitesmoke;
       }
    

    </style>
    <body> 
    <h2 id='policy-header'><%= @policy.title %></h2>
    <div class='policy_page_details'>
<br>
<h1>ABOUT THIS ISSUE</h1>
  <p id='policy_text'> <%= @policy.content %></p><br>
  <h2> Political Supporters</h2>
    <% if @policy.users.present? %>
        <% @policy.users.each do |user| %>
          <% if user.is_politician? %>
            <p><%= link_to user.name, user_path(user) %></p><br>
            <% end %>
        <% end %>
    <% else %>
        <p>Start a Trend! Become the First Person to Publicly Endorse This Position!</p>
    <% end %>
  </div>
  <div class='policy_pic'>
  <img src="<%= @policy.photo %>"><br>
  </div>
<br>

<br>
<div class='policy_navigation_links'>
<button><%= button_to "Add This Policy To Your Platform", action: 'add_policy_to_user', params: {user_id: session[:user_id], policy_id: @policy.id} %></button>
<br>
<button><%= button_to "Edit This Page", edit_policy_path(@policy), {method: :get} %></button>
<br>
<button><%= button_to "Back to Policies Page", policies_path, {method: :get} %></button>
</div>
</body>
</html>